spring:
  application:
    name: config-default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
